version: '2'
services:

  redis-master:
    image: redis:3.2
    command: redis-server /etc/redis.conf
    volumes:
#      - "./.data:/data"
      - "./redis.conf:/etc/redis.conf"
    ports:
      - "16061:16061"
 
  redis-slave:
    image: redis:3.2
    command: redis-server --slaveof redis-master 16061
    links:
      - redis-master
    volumes:
#      - "./.data:/data"
      - "./redis-slave.conf:/etc/redis.conf"

